// Code generated by command: go run asm.go -out ../match_amd64.s -stubs ../match_stub.go -pkg swisstable. DO NOT EDIT.

#include "textflag.h"

// func MatchByte(c uint8, buffer []byte) (mask uint32, ok bool)
// Requires: SSE2, SSSE3
TEXT ·MatchByte(SB), NOSPLIT, $0-37
	MOVQ buffer_len+16(FP), AX
	CMPQ AX, $0x10
	JGE  valid
	XORL AX, AX
	MOVL AX, mask+32(FP)
	MOVB $0x00, ok+36(FP)
	RET

valid:
	MOVBLZX  c+0(FP), AX
	MOVQ     buffer_base+8(FP), CX
	PXOR     X1, X1
	MOVD     AX, X0
	PSHUFB   X1, X0
	MOVOU    (CX), X1
	PCMPEQB  X1, X0
	PMOVMSKB X0, AX
	MOVL     AX, mask+32(FP)
	MOVB     $0x01, ok+36(FP)
	RET
