// Code generated by command: go run asm.go -out ../match_amd64.s -stubs ../match_stub.go -pkg swisstable. DO NOT EDIT.

package swisstable

func MatchByte(c uint8, buffer []byte) (mask uint32, ok bool)
