// Code generated by command: go run main.go -out match.s -stubs stub.go. DO NOT EDIT.

#include "textflag.h"

// func MatchByte(c uint8, buffer []byte) uint32
// Requires: SSE2, SSSE3
TEXT ·MatchByte(SB), NOSPLIT, $0-36
	MOVBLZX  c+0(FP), AX
	MOVQ     buffer_base+8(FP), CX
	PXOR     X1, X1
	MOVD     AX, X0
	PSHUFB   X1, X0
	PCMPEQB  (CX), X0
	PMOVMSKB X0, AX
	MOVL     AX, ret+32(FP)
	RET
